version: '3.4'

services:
  vtxchallenge:
    image: vtxchallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    links:
      - articleDb
  articleDb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:

